# action.yml
name: 'Zendesk App Tools - Deploy Apps'
author: 'Zendesk - Ashwin'
description: 'Create or Update an existing app in a Zendesk instance. Requires a .zat file.'
inputs:
  path:
    description: 'Path to the app directory to deploy'
    required: false
    default: '.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
